server:
  port: 8060
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: 
                  - "http://192.168.100.249:4200"
                  - "https://taskmanager-bf193.web.app"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: auth-service
              uri: lb://auth-service
              order: 1
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: JwtAuthFilter

            - id: auth-service
              uri: lb://auth-service
              order: 2
              predicates:
                - Path=/api/v1/user/**
              filters:
                - name: JwtAuthFilter

            - id: project-service
              uri: lb://project-service
              order: 3
              predicates:
                - Path=/api/v1/project/**
              filters:
                - name: JwtAuthFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
